# Generated by Django 3.0.3 on 2020-11-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_worker_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='start_date',
        ),
    ]
